import os



class ProjectTool:



    def create_project(self, params):


        path = params["path"]

        architecture = params["architecture"]



        os.makedirs(path, exist_ok=True)



        created = []



        for folder, files in architecture.items():


            folder_path = os.path.join(
                path,
                folder
            )


            os.makedirs(
                folder_path,
                exist_ok=True
            )


            for file in files:


                file_path = os.path.join(
                    folder_path,
                    file
                )


                with open(
                    file_path,
                    "w",
                    encoding="utf-8"
                ) as f:

                    f.write(
                        "# Generated by AI Agent\n"
                    )


                created.append(file_path)



        return {


            "status":"success",

            "created":created

        }
