import os


class ProjectBuilder:


    def create_project(self, architecture):


        root = architecture["name"]


        os.makedirs(
            root,
            exist_ok=True
        )


        for folder in architecture["folders"]:


            path = os.path.join(
                root,
                folder
            )


            os.makedirs(
                path,
                exist_ok=True
            )


        for file in architecture["files"]:


            path = os.path.join(
                root,
                file
            )


            directory = os.path.dirname(path)


            if directory:

                os.makedirs(
                    directory,
                    exist_ok=True
                )


            with open(
                path,
                "w",
                encoding="utf-8"
            ) as f:

                f.write(
                    "# Generated by AI Agent\n"
                )


        return {

            "status": "success",

            "project": root

        }
